services:
  dbase:
    container_name: postgres_db
    restart: always
    ports: 
      - '5431:5432'
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    image: postgres:14.9-alpine
  redis:
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    image: redis:alpine 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
volumes:
  redis:
    driver: local        